// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdnp7tkrF2XCL1i7YeHP8Hl692pS8SAt0',
    appId: '1:296982530054:web:2eeb9b01e0efc7694f5b87',
    messagingSenderId: '296982530054',
    projectId: 'quizapp-9440e',
    authDomain: 'quizapp-9440e.firebaseapp.com',
    storageBucket: 'quizapp-9440e.appspot.com',
    measurementId: 'G-PL14RQVV6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhwrvw9kiHlJVOuSTboZJK_77sE0I0j6U',
    appId: '1:296982530054:android:5e59e58467c30bc84f5b87',
    messagingSenderId: '296982530054',
    projectId: 'quizapp-9440e',
    storageBucket: 'quizapp-9440e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtM4rBTFj9qiroQOuMZKptr5W9uPCmqFw',
    appId: '1:296982530054:ios:1bb61014ab5b69064f5b87',
    messagingSenderId: '296982530054',
    projectId: 'quizapp-9440e',
    storageBucket: 'quizapp-9440e.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtM4rBTFj9qiroQOuMZKptr5W9uPCmqFw',
    appId: '1:296982530054:ios:1bb61014ab5b69064f5b87',
    messagingSenderId: '296982530054',
    projectId: 'quizapp-9440e',
    storageBucket: 'quizapp-9440e.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdnp7tkrF2XCL1i7YeHP8Hl692pS8SAt0',
    appId: '1:296982530054:web:f029b0dce4f6c16f4f5b87',
    messagingSenderId: '296982530054',
    projectId: 'quizapp-9440e',
    authDomain: 'quizapp-9440e.firebaseapp.com',
    storageBucket: 'quizapp-9440e.appspot.com',
    measurementId: 'G-RM1WB1RJEE',
  );
}
